### ISSUE TITLE
 Files Corrupted. Check logs

### ISSUE THREAD

**Issue by Murtazaaly01** [yashoswalyo/clone-bot-public#19]
-  **While uploading to telegram(a gdrive link or leeching a tg file) it gave `error([pyrogramEngine.py:306] - ERROR - invalid literal for int() with base 10)`.**
 

- **Uploading to drive working fine for both**

[My LOGS ](https://paste.ee/r/K5InH) 

- **This happened after last commit.**

**Comment by yashoswalyo** [comment]
are you using `CHANNEL_ID` variable?

**Comment by yashoswalyo** [comment]
fix was pushed today morning related to this, you can try and tell

**Comment by yashoswalyo** [comment]
You maybe doing mistake somewhere, No one is facing this error

**Comment by yashoswalyo** [comment]
Closing issue! join discussion group on telegram
